# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1537555-hpclab/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu7ev-ffvc1156-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName work
    rt::set_parameter defaultVhdlWorkLib work

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/2fcd/hdl
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog
  } {
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_2/synth/bd_afc3_s00mmu_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_3/synth/bd_afc3_s00tr_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_4/synth/bd_afc3_s00sic_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_5/synth/bd_afc3_s00a2s_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_6/synth/bd_afc3_sarn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_7/synth/bd_afc3_srn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_8/synth/bd_afc3_sawn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_9/synth/bd_afc3_swn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_10/synth/bd_afc3_sbn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_11/synth/bd_afc3_m00s2a_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_12/synth/bd_afc3_m00e_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_2/synth/bd_a878_s00mmu_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_3/synth/bd_a878_s00tr_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_4/synth/bd_a878_s00sic_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_5/synth/bd_a878_s00a2s_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_6/synth/bd_a878_sarn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_7/synth/bd_a878_srn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_8/synth/bd_a878_sawn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_9/synth/bd_a878_swn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_10/synth/bd_a878_sbn_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_11/synth/bd_a878_m00s2a_0.sv
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_12/synth/bd_a878_m00e_0.sv
    }
      rt::read_verilog -include {
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/2fcd/hdl
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ec67/hdl
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog
  } {
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0_4/hdl/zynq_ultra_ps_e_v3_5_1.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/0994/hdl/floating_point_v7_1_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/ip/acti_proc_fcmp_32ns_32ns_1_2_no_dsp_1_ip.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/ip/acti_proc_fmul_32ns_32ns_32_3_max_dsp_1_ip.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/ip/acti_proc_fadd_32ns_32ns_32_4_full_dsp_1_ip.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_xbar_0_4/synth/design_1_xbar_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/769c/hdl/axi_clock_converter_v2_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/670d/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0_4/synth/design_1_auto_ds_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0_4/synth/design_1_auto_pc_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_auto_ds_1_4/synth/design_1_auto_ds_1.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1_4/synth/design_1_auto_pc_1.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_0/synth/bd_afc3_one_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/synth/bd_afc3.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/synth/design_1_axi_smc_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_0/synth/bd_a878_one_0.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/synth/bd_a878.v
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/synth/design_1_axi_smc_1_0.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib work {
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/synth/design_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0_4/synth/design_1_zynq_ultra_ps_e_0_0.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_activ.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_ama_addmuladd_5ns_17ns_13ns_16ns_30_4_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_control_s_axi.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_fadd_32ns_32ns_32_4_full_dsp_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_fcmp_32ns_32ns_1_2_no_dsp_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_flow_control_loop_pipe_sequential_init.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_fmul_32ns_32ns_32_3_max_dsp_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_imem_m_axi.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_matmul.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_matmul_Pipeline_VITIS_LOOP_33_3_VITIS_LOOP_35_4.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_matmul_Pipeline_VITIS_LOOP_45_7.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_matmul_Pipeline_VITIS_LOOP_51_8.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_matmul_Pipeline_VITIS_LOOP_64_10.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_mem_m_axi.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_mul_13ns_13ns_26_1_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc_sparsemux_33_4_32_1_1.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/080f/hdl/vhdl/acti_proc.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_acti_proc_0_0_4/synth/design_1_acti_proc_0_0.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_100M_0_4/synth/design_1_rst_ps8_0_100M_0.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0_4/bd_0/ip/ip_1/synth/bd_afc3_psr_aclk_0.vhd
      /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ip/design_1_axi_smc_1_0_4/bd_0/ip/ip_1/synth/bd_a878_psr_aclk_0.vhd
    }
      rt::read_vhdl -lib xbip_utils_v3_0_11 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/9836/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/e392/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/c4f2/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_5 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/e5f6/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/9cc0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/0fb3/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/7a2e/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_19 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/e1b5/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_16 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/0994/hdl/floating_point_v7_1_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_7 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/3c0c/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_9 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_14 /home/bitstreambard/dma_ps/auto_synth/.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-1537555-hpclab/realtime/design_1_synth.xdc
    rt::sdcChecksum
    set rt::top design_1
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-1537555-hpclab/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1537555-hpclab/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
